#!/usr/bin/env bash
# One-time bootstrap: install narrow NOPASSWD sudoers entries on the pebble
# so scripts/deploy-to-pi.sh can run unattended. Requires the Pi sudo password
# the first time — prompted by ssh.
#
# Usage:
#   ./scripts/setup-pi-sudoers.sh                  # kode@pebble.local
#   PI_HOST=kode@10.0.0.42 ./scripts/setup-pi-sudoers.sh

set -euo pipefail

PI_HOST="${PI_HOST:-kode@pebble.local}"
PI_USER="${PI_HOST%@*}"
SUDOERS_FILE="/etc/sudoers.d/kode-os-deploy"

REMOTE_TMP="/tmp/kode-os-deploy.sudoers"
LOCAL_TMP=$(mktemp)
trap 'rm -f "${LOCAL_TMP}"' EXIT

cat > "${LOCAL_TMP}" <<EOF
# kode-os-deploy — NOPASSWD entries for scripts/deploy-to-pi.sh
# and scripts/deploy-screen-to-pi.sh. Generated by setup-pi-sudoers.sh.
${PI_USER} ALL=(root) NOPASSWD: /usr/bin/rsync -a /tmp/kode-os-ui/ /var/lib/casaos/www/
${PI_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart casaos-gateway
${PI_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart casaos
${PI_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart pebble-screen.service
${PI_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl is-active pebble-screen.service
EOF

echo "Uploading sudoers fragment to ${PI_HOST}:${REMOTE_TMP}..."
scp -q "${LOCAL_TMP}" "${PI_HOST}:${REMOTE_TMP}"

echo "Installing ${SUDOERS_FILE} (visudo will validate syntax first)..."
ssh -t "${PI_HOST}" "sudo /usr/sbin/visudo -c -f ${REMOTE_TMP} \
  && sudo install -m 440 -o root -g root ${REMOTE_TMP} ${SUDOERS_FILE} \
  && rm ${REMOTE_TMP} \
  && echo SUDOERS_INSTALLED"

echo ""
echo "Verifying NOPASSWD entries..."
ssh -o BatchMode=yes "${PI_HOST}" "sudo -n -l 2>&1 | grep -E '(rsync|systemctl restart casaos)' || true"

echo ""
echo "Done. ./scripts/deploy-to-pi.sh should now run without password prompts."
